### ISSUE TITLE
ViteとLaravelがそれぞれ異なる.envを読みにいってしまう

### ISSUE THREAD

**Issue by nonuplet** [mjtakenon/hakoniwa#153]
## Overview

現在の仕様では、ViteとLaravelがそれぞれ異なる `.env` ファイルを読みにいっているようです。
例: dev環境の場合
- `Laravel` -> `.env` をロード 
- `Vite` -> `.env.local` をロード

例えば `DEBUG_LOGIN_USING_ID` オプションを.env.localにのみ記載した場合、Laravelが `.env` 側を読みに行ってしまうためpropsが渡されず、フッターのデバッグにログインボタンが表示できないバグが現時点で発生しています。

影響範囲が計り知れないため早急に解決したいが、開発環境に影響を及ぼしてしまうため要検討事案…

**Comment by mjtakenon** [comment]
これそもそも同じenvを見に行ったとしてもかなり困るかもしれん
同じキーで違う値を渡せないのと、不要な環境変数がわたってしまい事故の元になりそう

読み込むenvは指定できなさそうなので、となるとやはりディレクトリを切るしか...?

**Comment by nonuplet** [comment]
う〜ん悩ましいところ…

特段問題になるのが `.env.local` という名称が Vite の予約語になっていることなので、差し支えなければそれだけ名称変更するとかも無きにしもあらず…？

https://ja.vitejs.dev/guide/env-and-mode.html#env-files

**Comment by nonuplet** [comment]
fixed #158
