### ISSUE TITLE
実績獲得・閲覧機能

### ISSUE THREAD

**Issue by nonuplet** [mjtakenon/hakoniwa#38]
モチベのためにあると嬉しい？
ただ負荷がどの程度かかるか要検証

**Comment by mjtakenon** [comment]
既存の箱庭は以下のものがあるがどこまで用意するかは検討の余地あり
- ターン賞
- 繁栄賞、災難賞
- 怪獣討伐
https://hakopedia.uhyohyo.net/wiki/%E8%B3%9E%E4%B8%80%E8%A6%A7

**Comment by mjtakenon** [comment]
𝓭𝓸𝓷𝓮...
