### ISSUE TITLE
jsのファイル取得時にビルド番号をつける

### ISSUE THREAD

**Issue by mjtakenon** [mjtakenon/hakoniwa#39]
- キャッシュが効いちゃうのなんとかしたいだけ

**Comment by nonuplet** [comment]
rollupOptionsでファイル名を固定にしてるのが原因だと思います。
たぶん手間かからないので修正しておきます。
https://github.com/mjtakenon/hakoniwa/blob/c6115d1f400ab4c24a78357541ad56e17f5c4d02/app/vite.config.js#L23-L31

**Comment by mjtakenon** [comment]
対応済み
天才
