### ISSUE TITLE
島の最後を看取れる機能

### ISSUE THREAD

**Issue by Mizune** [mjtakenon/hakoniwa#42]
島が死んだ後になぜ島が滅んだのかを見れるようにしたい

死んだ島を自分で放棄してから新しい島に移行する?

**Comment by mjtakenon** [comment]
@Mizune 
人口ゼロでは島が死なないようにした。代償として発展ポイントは半分になる
代わりに、既定ターン数資金繰りを繰り返すと放置される設定を追加
この設定は現環境では一旦無効にしている
これで良ければクローズで
