### ISSUE TITLE
エラーページの実装

### ISSUE THREAD

**Issue by rain825** [mjtakenon/hakoniwa#44]
## 概要
例外発生時のハンドリングがされてなさそうなので、簡易エラーページくらいは表示したい

**Comment by mjtakenon** [comment]
429.blade.phpだけはあるので、コピペで作るのが早いかも

**Comment by mjtakenon** [comment]
雑にですが、404, 419, 500, 503ページは実装しました。

**Comment by rain825** [comment]
<img width="870" alt="image" src="https://github.com/mjtakenon/hakoniwa/assets/19408972/3ea352e1-2da0-4444-9b06-43fcfde3c0e9">

良さげ
