### ISSUE TITLE
ログインユーザー情報の補完

### ISSUE THREAD

**Issue by rain825** [mjtakenon/hakoniwa#50]
## 概要
Yahooログインだとusernameが取得できないため、ユーザー情報登録時には適当な文字列を仮で入れてます。これを島作成時にownernameで書き換えたいです。
Googleの方は要検討

**Comment by mjtakenon** [comment]
@rain825 
島名で表示するようになりましたので、ランダム値は出なくなりました。
適当な文字列は引き続きDBに保存されているんですけれど、ユーザーの目には触れないのでクローズします。

**Comment by rain825** [comment]
@mjtakenon 
>島名で表示するようになりましたので、ランダム値は出なくなりました。

承知ですー。いいと思います。
ちなみに、usersテーブルのusernameはどうします？ islandsのオーナー名があるし、特に役割がないなら二重管理になるから `users`テーブルからは消していいのではと思いました

**Comment by mjtakenon** [comment]
> ちなみに、usersテーブルのusernameはどうします？ islandsのオーナー名があるし、特に役割がないなら二重管理になるから `users`テーブルからは消していいのではと思いました

@rain825 
もしかしたらアカウント統合するなら使うかな？？？と思ったんですがまあそんなことは当分しないと思うので消しちゃいます

**Comment by mjtakenon** [comment]
ついでにrememberTokenも一生使わなそうなので消します
